//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HeroVillageDLL
{
	public class CEStructure : BClickableEntity<CEStructure>
	{
		public string name { get; private set; }

		public CEStructure (string name)
		{
			this.name = name;
		}

		public override void notify ()
		{
			observers.ForEach (delegate(BIObserver<CEStructure> obj) {
				obj.update (this, EventState.CLICKED);
			});
		}

		public override string ToString ()
		{
			return string.Format ("[CEStructure] : {0}", name);
		}

	}
}

