//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HeroVillageDLL
{
	public enum EventState
	{
//		ENTITY_CLICKED,				// This occurs when an entity is clicked
//		STRUCTURE_CLICKED,			// This occurs when a structure is clicked
//		ITEM_CLICKED,				// This occurs when an item is clicked

		CLICKED,						// This is the new method of handling events. Instead of an event for each type, theres the general events
		DRAGGED,							// This could be a method later for dragging items onto a person or structure for some purpose. Maybe crafting? or using the item being dragged as a context?
		TIMER_UPDATE
	}
}

