//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HeroVillageDLL
{
	public interface BISubject<O>
	{
		void attach (O observer);
		void dettach (O observer);
		void notify ();
	}
}

