//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
namespace HeroVillageDLL
{
	public abstract class BClickableEntity<E> : BISubject<BIObserver<E>>
	{
		public List<BIObserver<E>> observers { get; private set; }

		public BClickableEntity ()
		{
			observers = new List<BIObserver<E>> ();
		}

		public void attach (BIObserver<E> observer)
		{
			observers.Add (observer);
		}

		public void dettach (BIObserver<E> observer)
		{
			observers.Remove (observer);
		}

		abstract public void notify ();
	}
}

